// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lcfpdlspgspfdjqwrbpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxjZnBkbHNwZ3NwZmRqcXdyYnB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzE2MDIsImV4cCI6MjA3MDI0NzYwMn0.TxtIC4afvILGWg5JYWGiWk7C9u6jys7nlcA17IWLdpk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});